### ISSUE TITLE
Change format_phone_number to include double zero convention

### ISSUE THREAD

**Issue by Kpaubert** [AndreasWintherMoen/jobb#26]
Currently, the utility function format_phone_number checks if the phone_number includes a country code. It does this by checking if the number starts with a plus sign, "+". Another way of assigning a country code is by starting the phone number with two zeroes, "00". It's not necessarily an important change, since most people use the plus convention (if any) - but it could be an idea to check if a phone number starts with "00" so the function doesn't return weird numbers.

| Convention    | Phone number | Number after format_phone_number |
|---------------|--------------|----------------------------------|
| No convention | 12345678     | +4712345678                      |
| Plus          | +4712345678  | +4712345678                      |
| Double zero   | 004712345678 | +47004712345678                  |

**Comment by AndreasWintherMoen** [comment]
The reason I have that function in the first place is because Twilio [requires a plus format](https://support.twilio.com/hc/en-us/articles/223183008-Formatting-International-Phone-Numbers) (E.164 formatting), but most OW users don't add a country code. So the function basically just appends +47 to those numbers, as well as removing any whitespace. I don't think I've seen anyone use the 00 format in OW, but I can take a look. 

![bitmoji](https://sdk.bitmoji.com/render/panel/f3212f5b-a4ce-412e-8baa-add05b41e04e-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)

**Comment by Kpaubert** [comment]
Closing this due to staleness and irrelevance.
